export const ADMIN_ROUTER = '/admin'
export const LOGIN_ROUTER = '/login'
export const REGISTRATION_ROUTER = '/registration'
export const MAIN_ROUTER = '/'
export const MUSIC_ROUTER = '/music'
export const ALL_MUSIC_ROUTER = '/allMusic'
export const ALBUM_ROUTER = '/album'
export const GENRES_ROUTER = '/genres'
export const PROD_ROUTER = '/prod'
export const ERROR = '*'

export const REACT_APP_API_URL = 'http://localhost:5050/'